apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-self-healing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-self-healing
  template:
    metadata:
      labels:
        app: ml-self-healing
    spec:
      containers:
        - name: ml-self-healing
          image: ml-lab-02:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
