apiVersion: batch/v1
kind: Job
metadata:
  name: train-model
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: trainer
          image: ml-lab-06:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: model-storage
              mountPath: /models
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-storage
